litellm_settings:
  success_callback: ["langfuse"]
  drop_params: true

model_list:
  - model_name: claude-3-7-sonnet-20250219 # RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: claude-3-7-sonnet-20250219 # MODEL NAME sent to `litellm.completion()` ###
      api_key: "os.environ/ANTHROPIC_API_KEY" # does os.getenv("AZURE_API_KEY_EU")
  - model_name: gpt-4.1 # RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: gpt-4.1 # MODEL NAME sent to `litellm.completion()` ###
      api_key: "os.environ/OPENAI_API_KEY" # does os.getenv("AZURE_API_KEY_EU")
  - model_name: gpt-4o # RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: gpt-4o # MODEL NAME sent to `litellm.completion()` ###
      api_key: "os.environ/OPENAI_API_KEY" # does os.getenv("AZURE_API_KEY_EU")
  - model_name: secmlr/final_model # RECEIVED MODEL NAME ###
    litellm_params: # all params accepted by litellm.completion() - https://docs.litellm.ai/docs/completion/input
      model: hosted_vllm/secmlr/final_model # MODEL NAME sent to `litellm.completion()` ###
      api_key: virtueai7355608
      api_base: http://0.0.0.0:25002/v1